name: greggs_test_basket_service
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  greggs_test_data_models:
    path: ../greggs_test_data_models
  rxdart: ^0.27.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
