name: greggs_test_data_models
description: Data models for the greggs_test application
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  freezed_annotation: ^2.1.0
  json_annotation: ^4.1.0

dev_dependencies:
  build_runner:  ^2.1.4
  freezed: ^2.1.0+1
  test: ^1.18.2
  json_serializable: ^6.3.1
